export const metersAndGroupFactory = 
    {
        "data": [
            {
                "meter_id": 16,
                "meter_name": "newmeter1",
                "meter_description": "descriptionmeter",
                "meter_type": "gauge",
                "uom_id": 1,
                "meter_reading_type_id": 1,
                "meter_domain_id": 7,
                "created_at": "2024-11-26T08:18:57.110491Z",
                "updated_at": "2024-11-26T08:18:57.110491Z",
                "created_by": "green",
                "updated_by": "green",
                "uom_name": "B34",
                "uom_description": "Kilogram/cubic decimeter",
                "meter_reading_type_value": "ACTUAL",
                "meter_reading_type_description": "Actual readings",
                "domain": "CALTYPE",
                "domain_description": "Calendar Type"
            },
            {
                "meter_id": 14,
                "meter_name": "Meter example 1 intercepted",
                "meter_description": "Meter description example here",
                "meter_type": "gauge",
                "uom_id": 1,
                "meter_reading_type_id": null,
                "meter_domain_id": null,
                "created_at": "2024-05-15T03:37:58.39745Z",
                "updated_at": "2024-05-15T03:37:58.39745Z",
                "created_by": "green",
                "updated_by": "green",
                "uom_name": "B34",
                "uom_description": "Kilogram/cubic decimeter",
                "meter_reading_type_value": null,
                "meter_reading_type_description": null,
                "domain": null,
                "domain_description": null
            },
            {
                "meter_id": 12,
                "meter_name": "Nez Test Meter",
                "meter_description": "Hanya testing",
                "meter_type": "gauge",
                "uom_id": 2,
                "meter_reading_type_id": 2,
                "meter_domain_id": 1,
                "created_at": "2024-05-08T14:36:06.377007Z",
                "updated_at": "2024-05-17T06:54:49.752576Z",
                "created_by": "green",
                "updated_by": "green",
                "uom_name": "B45",
                "uom_description": "Kilomol",
                "meter_reading_type_value": "DELTA",
                "meter_reading_type_description": "Delta Readings",
                "domain": "DMCOLLVALIDRESULT",
                "domain_description": "Need description"
            },
            {
                "meter_id": 9,
                "meter_name": "Test Meter Gauge",
                "meter_description": "gauge meter desc edit to continuoius",
                "meter_type": "continuous",
                "uom_id": 1,
                "meter_reading_type_id": 1,
                "meter_domain_id": 2,
                "created_at": "2024-05-02T09:38:15.796064Z",
                "updated_at": "2024-11-25T08:57:45.338108Z",
                "created_by": "green",
                "updated_by": "green",
                "uom_name": "B34",
                "uom_description": "Kilogram/cubic decimeter",
                "meter_reading_type_value": "ACTUAL",
                "meter_reading_type_description": "Actual readings",
                "domain": "SCRLAUNCHPNTTYPE",
                "domain_description": "Script launch point"
            },
            {
                "meter_id": 8,
                "meter_name": "character meter",
                "meter_description": "character",
                "meter_type": "characteristic",
                "uom_id": 1,
                "meter_reading_type_id": 1,
                "meter_domain_id": 1,
                "created_at": "2024-04-30T04:54:00.882701Z",
                "updated_at": "2024-04-30T04:54:00.882701Z",
                "created_by": "green",
                "updated_by": "green",
                "uom_name": "B34",
                "uom_description": "Kilogram/cubic decimeter",
                "meter_reading_type_value": "ACTUAL",
                "meter_reading_type_description": "Actual readings",
                "domain": "DMCOLLVALIDRESULT",
                "domain_description": "Need description"
            },
        ],
        "total": 5
    }

